// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwftjqsunctffcbryqhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3ZnRqcXN1bmN0ZmZjYnJ5cWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1Mzg5NjgsImV4cCI6MjA4NjExNDk2OH0.AXVaoYWA8wST72S95QsE1FI03CkieAC--h96JRQhJt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});